#서버 설정
server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
# 뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/cashbook/
      suffix: .jsp

# DataSource 실행
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 1234
